export { getResolvedConfiguration } from './application/configure.js';
export {
  DEFAULT_CONFIGURATION,
  resolveConfiguration,
  type ConfigurationOverrides,
  type ResolvedConfiguration,
} from './domain/config.js';
export { createTestCaseId } from './adapters/test-case-identity.js';
export {
  type AssertionApi,
  type AssertionRecord,
  type Diagnostic,
  type DiagnosticSeverity,
  type DynamicMetadataReason,
  type DynamicMetadata,
  type HookKind,
  type ImportKind,
  type HookRecord,
  type ImportRecord,
  type MockApi,
  type MockRecord,
  type DynamicParameterization,
  type NoParameterization,
  type ParameterizationMetadata,
  type StaticParameterization,
  type SourcePosition,
  type SourceSpan,
  type StaticParameterCase,
  type StaticParameterIdentity,
  type StructuralAncestrySegment,
  type TestCase,
  type TestCaseId,
  type TestCaseIdInput,
  type TestCaseKind,
  type TestFramework,
  type TestModifier,
  type TestModifierKind,
} from './domain/test-understanding.js';
